package Tests;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import java.util.LinkedList;
import AST.*;
import Tran.*;
public class Example2ParserTest {

	@Test
	public void Example2ParserTestTest() throws Exception {
		var tokens = new LinkedList<Token>();
		tokens.add(new Token(Token.TokenTypes.CLASS, 1, 5));
		tokens.add(new Token(Token.TokenTypes.WORD, 1, 14, "Example2"));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 2, 0));
		tokens.add(new Token(Token.TokenTypes.INDENT, 2, 4));
		tokens.add(new Token(Token.TokenTypes.WORD, 2, 10, "number"));
		tokens.add(new Token(Token.TokenTypes.WORD, 2, 12, "x"));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 3, 0));
		tokens.add(new Token(Token.TokenTypes.WORD, 3, 10, "string"));
		tokens.add(new Token(Token.TokenTypes.WORD, 3, 12, "y"));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 4, 0));
		tokens.add(new Token(Token.TokenTypes.CONSTRUCT, 4, 13));
		tokens.add(new Token(Token.TokenTypes.LPAREN, 4, 14));
		tokens.add(new Token(Token.TokenTypes.RPAREN, 4, 15));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 5, 0));
		tokens.add(new Token(Token.TokenTypes.INDENT, 5, 8));
		tokens.add(new Token(Token.TokenTypes.WORD, 5, 9, "x"));
		tokens.add(new Token(Token.TokenTypes.ASSIGN, 5, 11));
		tokens.add(new Token(Token.TokenTypes.NUMBER, 5, 13, "0"));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 6, 0));
		tokens.add(new Token(Token.TokenTypes.WORD, 6, 9, "y"));
		tokens.add(new Token(Token.TokenTypes.ASSIGN, 6, 11));
		tokens.add(new Token(Token.TokenTypes.QUOTEDSTRING, 6, 14));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 7, 0));
		tokens.add(new Token(Token.TokenTypes.DEDENT, 7, 4));
		tokens.add(new Token(Token.TokenTypes.WORD, 7, 14, "doSomeWork"));
		tokens.add(new Token(Token.TokenTypes.LPAREN, 7, 15));
		tokens.add(new Token(Token.TokenTypes.RPAREN, 7, 16));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 8, 0));
		tokens.add(new Token(Token.TokenTypes.INDENT, 8, 8));
		tokens.add(new Token(Token.TokenTypes.WORD, 8, 9, "x"));
		tokens.add(new Token(Token.TokenTypes.ASSIGN, 8, 10));
		tokens.add(new Token(Token.TokenTypes.NUMBER, 8, 12, "10"));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 9, 0));
		tokens.add(new Token(Token.TokenTypes.LOOP, 9, 12));
		tokens.add(new Token(Token.TokenTypes.WORD, 9, 14, "x"));
		tokens.add(new Token(Token.TokenTypes.DOT, 9, 15));
		tokens.add(new Token(Token.TokenTypes.WORD, 9, 20, "times"));
		tokens.add(new Token(Token.TokenTypes.LPAREN, 9, 21));
		tokens.add(new Token(Token.TokenTypes.RPAREN, 9, 22));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 10, 0));
		tokens.add(new Token(Token.TokenTypes.INDENT, 10, 12));
		tokens.add(new Token(Token.TokenTypes.WORD, 10, 19, "console"));
		tokens.add(new Token(Token.TokenTypes.DOT, 10, 20));
		tokens.add(new Token(Token.TokenTypes.WORD, 10, 25, "print"));
		tokens.add(new Token(Token.TokenTypes.LPAREN, 10, 26));
		tokens.add(new Token(Token.TokenTypes.QUOTEDSTRING, 10, 40, "In The Block"));
		tokens.add(new Token(Token.TokenTypes.RPAREN, 10, 41));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 11, 0));
		tokens.add(new Token(Token.TokenTypes.DEDENT, 11, 8));
		tokens.add(new Token(Token.TokenTypes.WORD, 11, 15, "console"));
		tokens.add(new Token(Token.TokenTypes.DOT, 11, 16));
		tokens.add(new Token(Token.TokenTypes.WORD, 11, 21, "print"));
		tokens.add(new Token(Token.TokenTypes.LPAREN, 11, 22));
		tokens.add(new Token(Token.TokenTypes.QUOTEDSTRING, 11, 40, "Out of the block"));
		tokens.add(new Token(Token.TokenTypes.RPAREN, 11, 41));
		tokens.add(new Token(Token.TokenTypes.NEWLINE, 12, 0));
		tokens.add(new Token(Token.TokenTypes.DEDENT, 12, 0));
		tokens.add(new Token(Token.TokenTypes.DEDENT, 12, 0));
		var tran = new TranNode();
		var p = new Parser(tran,tokens);
		p.Tran();
		Assertions.assertEquals(1,tran.Classes.size());
		Assertions.assertEquals("Example2",tran.Classes.get(0).name);
		Assertions.assertEquals(0,tran.Classes.get(0).interfaces.size());
		Assertions.assertEquals(1,tran.Classes.get(0).constructors.size());
		Assertions.assertEquals(0,tran.Classes.get(0).constructors.get(0).parameters.size());
		Assertions.assertEquals(2,tran.Classes.get(0).constructors.get(0).statements.size());
		Assertions.assertEquals("x",((VariableReferenceNode)((AssignmentNode)tran.Classes.get(0).constructors.get(0).statements.get(0)).target).name);
		Assertions.assertEquals(0,((NumericLiteralNode)((AssignmentNode)tran.Classes.get(0).constructors.get(0).statements.get(0)).expression).value);
		Assertions.assertEquals("y",((VariableReferenceNode)((AssignmentNode)tran.Classes.get(0).constructors.get(0).statements.get(1)).target).name);
		Assertions.assertEquals("",((StringLiteralNode)((AssignmentNode)tran.Classes.get(0).constructors.get(0).statements.get(1)).expression).value);
		Assertions.assertEquals(1,tran.Classes.get(0).methods.size());
		Assertions.assertEquals("doSomeWork",((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).name);
		Assertions.assertEquals(3,((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.size());
		Assertions.assertEquals("x",((VariableReferenceNode)((AssignmentNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(0)).target).name);
		Assertions.assertEquals(10,((NumericLiteralNode)((AssignmentNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(0)).expression).value);
		Assertions.assertEquals(1,((LoopNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(1)).statements.size());
		Assertions.assertEquals("print",((MethodCallStatementNode)((LoopNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(1)).statements.get(0)).methodName);
		Assertions.assertEquals("In The Block",((StringLiteralNode)((MethodCallStatementNode)((LoopNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(1)).statements.get(0)).parameters.get(0)).value);
		Assertions.assertEquals("console",((MethodCallStatementNode)((LoopNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(1)).statements.get(0)).objectName.orElseThrow());
		Assertions.assertEquals("times",((MethodCallExpressionNode)((LoopNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(1)).expression).methodName);
		Assertions.assertEquals("x",((MethodCallExpressionNode)((LoopNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(1)).expression).objectName.get());
		Assertions.assertEquals("print",((MethodCallStatementNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(2)).methodName);
		Assertions.assertEquals("Out of the block",((StringLiteralNode)((MethodCallStatementNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(2)).parameters.get(0)).value);
		Assertions.assertEquals("console",((MethodCallStatementNode)((MethodDeclarationNode)tran.Classes.get(0).methods.get(0)).statements.get(2)).objectName.orElseThrow());
		Assertions.assertEquals(2,tran.Classes.get(0).members.size());
		Assertions.assertEquals("x",((MemberNode)tran.Classes.get(0).members.get(0)).declaration.name);
		Assertions.assertEquals("number",((MemberNode)tran.Classes.get(0).members.get(0)).declaration.type);
		Assertions.assertEquals("y",((MemberNode)tran.Classes.get(0).members.get(1)).declaration.name);
		Assertions.assertEquals("string",((MemberNode)tran.Classes.get(0).members.get(1)).declaration.type);
		Assertions.assertEquals(0,tran.Interfaces.size());
	}
}
